apiVersion: v1
kind: Service
metadata:
  name: devops-exam-service
spec:
  selector:
    app: devopsexamapp  # Updated to match your deployment's label
  type: NodePort
  ports:
    - protocol: TCP
      port: 80            # External port for clients
      targetPort: 5000    # Internal container port your app listens on
      nodePort: 32123     # Manually chosen NodePort (must be in 30000–32767)
